networks:
  db:
    driver: bridge
  cache:
    driver: bridge


services:
  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - db
      - cache

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
    networks:
      - db
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    networks:
      - db
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    networks:
      - cache
