# ===================================================================
# SERVER CONFIGURATION
# ===================================================================
server:
  port: 8080

# ===================================================================
# SPRING BOOT CONFIGURATION
# ===================================================================
spring:
  # --- Spring Active Profile Configuration ---
  profiles:
    active: dev
  application:
    name: BonreCreme-Restaurant

